# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for FTHR Clips — Windows bundle.
# Run on Windows: pyinstaller FTHR.spec --clean
from pathlib import Path
import glob as _glob
import sys as _sys

ROOT       = Path(SPECPATH)
UI_DIR     = ROOT / 'FTHR_UI'
ASSETS_DIR = UI_DIR / 'assets'

# Product version comes from FTHR_UI/version.py — never retype it here.
_sys.path.insert(0, str(UI_DIR))
from version import (                     # noqa: E402
    __version__ as APP_VERSION, APP_NAME, APP_ID, PUBLISHER,
    windows_file_version,
)

# Windows VERSIONINFO resource. Without this the shipped .exe reports no
# version at all in Explorer -> Properties -> Details, which made "which build
# are you running?" unanswerable for alpha bug reports.
_VER_FILE = ROOT / 'build' / 'version_win.txt'
_VER_FILE.parent.mkdir(parents=True, exist_ok=True)
_VER_FILE.write_text(f"""\
# Generated by FTHR.spec from FTHR_UI/version.py — do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={windows_file_version()},
    prodvers={windows_file_version()},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName',      {PUBLISHER!r}),
        StringStruct('FileDescription',  {APP_NAME + ' — game capture and clip management'!r}),
        StringStruct('FileVersion',      {APP_VERSION!r}),
        StringStruct('InternalName',     {APP_ID!r}),
        StringStruct('OriginalFilename', {APP_ID + '.exe'!r}),
        StringStruct('ProductName',      {APP_NAME!r}),
        StringStruct('ProductVersion',   {APP_VERSION!r}),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding='utf-8')
ENGINE_EXE = ROOT / 'FTHRcapture' / 'x64' / 'Release' / 'FTHRClips.exe'
PLAYBACK_MIXER = (ROOT / 'FTHRcapture' / 'FTHRPlaybackMixer' / 'x64'
                  / 'Release' / 'FTHRPlaybackMixer.dll')

# FFmpeg DLLs the C++ engine links against on Windows
_FFMPEG_BIN  = ROOT / 'FTHRcapture' / 'FTHRclips' / 'third_party' / 'ffmpeg' / 'bin'
_FFMPEG_DLLS = _glob.glob(str(_FFMPEG_BIN / '*.dll'))
# ffmpeg.exe / ffprobe.exe from the SAME LGPL build. The Python side shells
# out to these for mic mux, watermark, auto-crop, webcam overlay and export.
# They were previously taken from imageio-ffmpeg, which (a) is GPL and
# (b) was never actually bundled — so all of the above silently no-opped.
_FFMPEG_TOOLS = [str(_FFMPEG_BIN / n) for n in ('ffmpeg.exe', 'ffprobe.exe')]

a = Analysis(
    [str(UI_DIR / 'main.py')],
    pathex=[str(UI_DIR)],
    binaries=[
        (str(ENGINE_EXE), 'engine'),
        # In-process FFmpeg decoder bridge used by the Qt clip viewer. It is
        # built from the pinned LGPL FFmpeg headers/libraries and shares the
        # exact runtime DLL set already shipped for the capture engine.
        (str(PLAYBACK_MIXER), 'engine'),
        *[(dll, 'engine') for dll in _FFMPEG_DLLS],
        *[(exe, 'engine') for exe in _FFMPEG_TOOLS],
    ],
    datas=[
        (str(ASSETS_DIR / 'fthr_logo.png'),   'assets'),
        # Licence paperwork must travel INSIDE the bundle (AUDIT-005), so a
        # portable copy is as complete as an installed one.
        (str(ROOT / 'LICENSE'), '.'),
        (str(ROOT / 'THIRD_PARTY_NOTICES.md'), '.'),
        (str(ROOT / 'licenses'), 'licenses'),
        (str(ROOT / 'tools' / 'release_asset_manifest.json'), 'licenses'),
        (str(ASSETS_DIR / 'fonts'),            'assets/fonts'),
        (str(ASSETS_DIR / 'icons'),            'assets/icons'),
        (str(ASSETS_DIR / 'sounds'),           'assets/sounds'),
        (str(UI_DIR / 'ui' / 'capture_card_process.py'), 'ui'),
    ],
    hiddenimports=[
        # stdlib networking — urllib.request imports http at runtime
        'http',
        'http.client',
        'http.cookiejar',
        'urllib',
        'urllib.request',
        'urllib.error',
        'urllib.parse',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtNetwork',
        'sounddevice',
        'numpy',
        'cv2',
        'keyboard',
        # UI submodules
        'ui.capture_card',
        'ui.capture_card_client',
        'ui.capture_card_process',
        'ui.capture_settings_widget',
        'ui.clip_grid',
        'ui.clip_viewer',
        'ui.customize_page',
        'ui.app_style',
        'ui.screenshot_editor',
        'ui.splash_screen',
        'ui.style',
        'ui.upload_settings_widget',
        # Core submodules
        'core.audio_mixer',
        'core.camera_recorder',
        'core.capture_bridge',
        'core.focus_monitor',
        'core.ffmpeg_playback',
        'core.game_detector',
        'core.hotkey_manager',
        'core.instance_activation',
        'core.mic_recorder',
        'core.presets_manager',
        'core.settings_manager',
        'core.theme_manager',
        'core.upload_manager',
        'core.windows_autostart',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # imageio_ffmpeg is deliberately EXCLUDED (AUDIT-005).
        # Its bundled binary is a gyan.dev build configured with
        # --enable-gpl --enable-libx264 --enable-libx265, i.e. GPLv3.
        # Shipping it would place this whole artifact under the GPL.
        # FTHR uses the LGPL FFmpeg next to the engine — see
        # FTHR_UI/core/ffmpeg_tools.py.
        'imageio_ffmpeg',
        # Qt modules unused on Windows (no Wayland, no QML)
        'PySide6.QtQuick', 'PySide6.QtQml', 'PySide6.QtWebEngine',
        'PySide6.QtWebEngineCore', 'PySide6.QtBluetooth', 'PySide6.QtPositioning',
        'PySide6.QtSensors', 'PySide6.QtLocation', 'PySide6.Qt3D',
        'PySide6.QtPdf', 'PySide6.QtPdfWidgets', 'PySide6.QtNfc',
        # GPL-only Qt modules are outside the reviewed LGPL runtime.
        'PySide6.QtCanvasPainter', 'PySide6.QtCoap', 'PySide6.QtGraphs',
        'PySide6.QtGrpc', 'PySide6.QtHttpServer', 'PySide6.QtLottie',
        'PySide6.QtMqtt', 'PySide6.QtNetworkAuth', 'PySide6.QtQmlCompiler',
        'PySide6.QtQuick3D', 'PySide6.QtVirtualKeyboard',
        'PySide6.QtWaylandCompositor',
        # Standard library bloat
        'tkinter', 'unittest',
        'pydoc', 'doctest', 'difflib', 'ftplib', 'imaplib',
        'poplib', 'smtplib', 'telnetlib', 'nntplib',
        # Scientific stack not used
        'matplotlib', 'scipy', 'pandas', 'PIL', 'IPython',
        'sklearn', 'skimage', 'sympy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

# PyInstaller's QtGui hook collects every platform-input-context plugin,
# including Qt Virtual Keyboard. That module is GPL-only in Qt 6.11 and pulls
# the otherwise unused QML/Quick runtime with it. Python-module exclusions do
# not filter hook-added binaries, so prune that reviewed-unnecessary chain from
# the actual TOCs before COLLECT.
def _keep_reviewed_qt_runtime(entry):
    dest = str(entry[0]).replace('\\', '/').casefold()
    name = dest.rsplit('/', 1)[-1]
    forbidden_prefixes = ('qt6qml', 'qt6quick', 'qt6virtualkeyboard')
    return ('virtualkeyboard' not in dest
            and not name.startswith(forbidden_prefixes))


a.binaries = [entry for entry in a.binaries
              if _keep_reviewed_qt_runtime(entry)]
a.datas = [entry for entry in a.datas
           if _keep_reviewed_qt_runtime(entry)]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_ID,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,      # strip doesn't work reliably on Windows DLLs
    upx=True,
    console=False,
    icon=str(ASSETS_DIR / 'fthr_logo.ico'),
    version=str(_VER_FILE),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[
        # Don't UPX-compress these — they either break or gain nothing
        'vcruntime*.dll', 'api-ms-*.dll', 'msvcp*.dll',
        'FTHRClips.exe',  # the Python app launcher
        'FTHRPlaybackMixer.dll',  # loaded through ctypes at viewer runtime
    ],
    name=APP_ID,
)
