// audio_source_model.h
// Common, clip-local audio-source contracts for AUDIT-050.
//
// This file deliberately contains no Windows process handles, executable paths,
// or shared-memory fields.  Those are runtime-provider details; a completed
// clip needs only durable, privacy-bounded source semantics.

#pragma once
#ifndef FTHR_AUDIO_SOURCE_MODEL_H
#define FTHR_AUDIO_SOURCE_MODEL_H

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace fthr {

inline constexpr uint32_t kMaxRetainedAudioSources = 8;
// Default Mix is mandatory compatibility audio, not an application-source
// admission. A completed clip can therefore carry it plus the eight real app
// stems permitted by the provisional AUDIT-050 source cap.
inline constexpr uint32_t kMaxClipAudioTracks = kMaxRetainedAudioSources + 1;

enum class AudioSourceType : uint8_t {
    Application,
    Microphone,
    System,
};

enum class AudioSourceHealth : uint8_t {
    Discovered,
    Active,
    Ended,
    Degraded,
    Failed,
};

// A UUID-shaped opaque identifier. It is generated by the provider and is the
// only source key which crosses the recording/runtime boundary.
struct AudioSourceId {
    std::string value;

    bool IsValid() const;
    bool operator<(const AudioSourceId& other) const { return value < other.value; }
    bool operator==(const AudioSourceId& other) const { return value == other.value; }
};

struct AudioSourceIdentity {
    AudioSourceId id;
    AudioSourceType type = AudioSourceType::Application;

    // A local, app/package/executable identity safe for manifest persistence.
    // It must never contain a path, command line, username, window title, URL,
    // or server address.
    std::string persistent_identity;
    std::string display_name;
    std::string icon_reference;
};

struct AudioSourceFormat {
    uint32_t sample_rate = 48000;
    uint32_t channels = 2;
    std::string sample_format = "fltp";
};

struct AudioSourceState {
    AudioSourceHealth health = AudioSourceHealth::Discovered;
    bool admitted = false;
    bool active_in_generation = false;
    int64_t first_active_100ns = -1;
    int64_t last_active_100ns = -1;
    uint32_t failure_count = 0;
};

struct AudioSourceMetadata {
    AudioSourceIdentity identity;
    AudioSourceFormat format;
    AudioSourceState state;
};

struct AudioActivityGateConfig {
    float activate_rms = 0.010f;
    float deactivate_rms = 0.003f;
    uint32_t activate_blocks = 2;
    uint32_t deactivate_blocks = 10;
};

// Cheap per-callback activity state. Hysteresis rejects the digital-silence
// and near-zero noise floor which appear in WASAPI sessions.
class AudioActivityGate {
public:
    explicit AudioActivityGate(AudioActivityGateConfig config = {});

    bool Observe(float rms);
    bool IsActive() const { return active_; }
    void Reset();

private:
    AudioActivityGateConfig config_;
    uint32_t loud_blocks_ = 0;
    uint32_t quiet_blocks_ = 0;
    bool active_ = false;
};

enum class AudioSourceAdmission : uint8_t {
    Accepted,
    AlreadyAdmitted,
    RejectedAtCapacity,
    RejectedInvalidIdentity,
};

// Per-generation registry. PID and process handles belong in the Windows
// provider, not here. The registry retains ended sources until its generation
// is destroyed, so replay history survives a process exit long enough to save.
class AudioSourceRegistry {
public:
    explicit AudioSourceRegistry(uint64_t generation,
                                 uint32_t limit = kMaxRetainedAudioSources);

    uint64_t generation() const { return generation_; }
    uint32_t limit() const { return limit_; }
    size_t admitted_count() const { return admitted_count_; }

    bool Discover(AudioSourceMetadata metadata);
    AudioSourceAdmission ObserveActivity(const AudioSourceId& id,
                                         float rms,
                                         int64_t timestamp_100ns);
    void MarkEnded(const AudioSourceId& id, int64_t timestamp_100ns);
    void MarkFailed(const AudioSourceId& id);

    // Only real audible contributors within [start, end] are returned. The
    // result has a stable semantic ordering, never MP4 stream-index ordering.
    std::vector<AudioSourceMetadata> SourcesForInterval(
        int64_t start_100ns, int64_t end_100ns) const;
    const AudioSourceMetadata* Find(const AudioSourceId& id) const;

private:
    static int AdmissionPriority(AudioSourceType type);
    static int PresentationPriority(AudioSourceType type);

    uint64_t generation_;
    uint32_t limit_;
    uint32_t admitted_count_ = 0;
    std::map<AudioSourceId, AudioSourceMetadata> sources_;
    std::map<AudioSourceId, AudioActivityGate> gates_;
};

// Manifest-safe values are intentionally narrow. The returned value is not a
// filesystem path and cannot retain separators or control characters.
std::string SanitizeAudioSourceText(const std::string& value, size_t max_length);
const char* AudioSourceTypeName(AudioSourceType type);

}  // namespace fthr

#endif  // FTHR_AUDIO_SOURCE_MODEL_H
